export type EnvironmentVariableReference = {
  name: string;
  defaultValue?: string;
  description: string;
};

/** Canonical user-facing environment contract for the server and macOS launcher. */
export const ENVIRONMENT_VARIABLE_REFERENCE: readonly EnvironmentVariableReference[] = [
  { name: 'AGENT_SERVER_HOME', defaultValue: '~/.agent-server', description: 'Base directory for default agent, lock, log, database, and environment-file paths' },
  { name: 'AGENT_SERVER_AGENTS_DIR', defaultValue: '~/.agent-server/agents', description: 'Directory containing agent definition files' },
  { name: 'AGENT_SERVER_LOCK_DIR', defaultValue: '~/.agent-server/locks', description: 'Lock file directory' },
  { name: 'AGENT_SERVER_LOGS_DIR', defaultValue: '~/.agent-server/logs', description: 'Log directory' },
  { name: 'AGENT_SERVER_RUN_DB', defaultValue: '~/.agent-server/runs.db', description: 'SQLite run-history database. Use `:memory:` for ephemeral runs.' },
  { name: 'AGENT_SERVER_CHECK_INTERVAL_MS', defaultValue: '60000', description: 'How often to check schedules (ms)' },
  { name: 'AGENT_SERVER_PANEL_URL', description: 'Telemetry endpoint base URL (for Agent Panel)' },
  { name: 'AGENT_SERVER_PANEL_API_KEY', description: 'API key for telemetry' },
  { name: 'AGENT_SERVER_PANEL_ENABLED', defaultValue: 'true', description: 'Set to `false` to disable all panel traffic while retaining saved credentials' },
  { name: 'AGENT_SERVER_API_KEY', defaultValue: 'generated by `agent-server init`', description: 'Required local API key with a minimum of 16 characters' },
  { name: 'AGENT_SERVER_HEARTBEAT_MS', defaultValue: '30000', description: 'Heartbeat interval during runs (ms)' },
  { name: 'AGENT_SERVER_TELEMETRY_PROGRESS_MODE', defaultValue: 'live', description: 'Send sampled live progress or defer progress until the terminal payload (`live` or `batched`)' },
  { name: 'AGENT_SERVER_TELEMETRY_PROGRESS_SAMPLE_MS', defaultValue: '5000', description: 'Minimum interval between live progress posts (ms)' },
  { name: 'AGENT_SERVER_TELEMETRY_PROGRESS_MAX_ENTRIES', defaultValue: '50', description: 'Maximum accumulated progress entries per run' },
  { name: 'AGENT_SERVER_TELEMETRY_PROGRESS_INCLUDE_METADATA', defaultValue: 'false', description: 'Include full metadata on stored progress entries' },
  { name: 'AGENT_SERVER_PORT', defaultValue: '47821', description: 'HTTP API port' },
  { name: 'AGENT_SERVER_HOST', defaultValue: '127.0.0.1', description: 'HTTP bind host' },
  { name: 'AGENT_SERVER_TELEGRAM_BOT_TOKEN', description: 'Telegram bot token for interactive agents and notifications' },
  { name: 'AGENT_SERVER_TELEGRAM_CHAT_ID', description: 'Optional Telegram chat ID restriction' },
  { name: 'AGENT_SERVER_SLACK_BOT_TOKEN', description: 'Slack bot token. `SLACK_BOT_TOKEN` is also accepted.' },
  { name: 'AGENT_SERVER_SLACK_APP_TOKEN', description: 'Slack Socket Mode app token. `SLACK_APP_TOKEN` is also accepted.' },
  { name: 'AGENT_SERVER_LOCATION', description: 'Path to the agent-server repo root. Used by the macOS app to find the server.' },
  { name: 'AGENT_SERVER_CATCH_UP', defaultValue: 'false', description: 'Resume missed scheduled agents after sleep/wake' },
  { name: 'AGENT_SERVER_MAX_CONCURRENT_RUNS', defaultValue: '8', description: 'Maximum concurrent running agents before new triggers are rejected' },
  { name: 'AGENT_SERVER_MAX_TRIGGER_DEPTH', defaultValue: '10', description: 'Maximum number of outgoing agent-to-agent trigger edges in one branch' },
  { name: 'AGENT_SERVER_MAX_WS_CLIENTS', defaultValue: '100', description: 'Maximum simultaneous WebSocket clients' },
  { name: 'AGENT_SERVER_RUN_TIMEOUT_MS', defaultValue: '1800000', description: 'Default wall-clock run timeout in milliseconds. Set to `0` to disable.' },
  { name: 'AGENT_SERVER_DEFAULT_MAX_TURNS', defaultValue: '20', description: 'Default `max_turns` used when an agent omits `max_turns`' },
  { name: 'AGENT_SERVER_PROMPT_INJECTION_GUARD', defaultValue: 'true', description: 'Wrap untrusted user context in guarded delimiters and policy instructions before execution' },
  { name: 'AGENT_SERVER_PROMPT_INJECTION_STRICT', defaultValue: 'false', description: 'Reject suspicious user context (pattern-based) before execution' },
  { name: 'AGENT_SERVER_CLAUDE_PATH', description: 'Exact path to the required Claude Code executable' },
  { name: 'AGENT_SERVER_CODEX_PATH', description: 'Exact path to the required Codex executable' },
  { name: 'AGENT_SERVER_USE_INSTALLED_KIMI', defaultValue: 'true', description: 'Set to `false` to turn off installed Kimi Code discovery' },
  { name: 'AGENT_SERVER_KIMI_PATH', description: 'Exact path to the `kimi` executable. An invalid explicit path fails closed.' },
  { name: 'AGENT_SERVER_ANALYTICS_KEY', description: 'Product analytics project key. Injected by the macOS app at launch. Unset means analytics is off.' },
  { name: 'AGENT_SERVER_ANALYTICS_HOST', defaultValue: 'https://us.i.posthog.com', description: 'Product analytics ingest host' },
  { name: 'AGENT_SERVER_ANALYTICS_DISTINCT_ID', description: 'Per-install identifier passed down by the macOS app so both surfaces resolve to one person' },
  { name: 'AGENT_SERVER_ANALYTICS_OPT_OUT', defaultValue: 'true', description: 'Product analytics stays off until this is explicitly set to `false`. The value in `~/.agent-server/.env` wins over the shell so the macOS toggle reaches a running daemon.' },
  { name: 'ANTHROPIC_API_KEY', description: 'Anthropic API key. Required for Telegram message routing (agent selection via Haiku).' },
];

export function renderEnvironmentReferenceTable(): string {
  const rows = ENVIRONMENT_VARIABLE_REFERENCE.map(({ name, defaultValue, description }) => {
    const renderedDefault = defaultValue === 'generated by `agent-server init`'
      ? defaultValue
      : defaultValue ? `\`${defaultValue}\`` : '';
    return `| \`${name}\` | ${renderedDefault} | ${description} |`;
  });
  return [
    '| Variable | Default | Description |',
    '|---|---|---|',
    ...rows,
  ].join('\n');
}
